### ISSUE TITLE
Is there an intended way to dump logs to a file

### ISSUE THREAD

**Issue by dehboxturtle** [albinaask/Log#1]
Hi! I've been using your logger, it is very helpful. I was just curious if there was an intended way to dump logs to a file. I saw that it has a static var for a FileAccess in the source code but I couldn't find any usage of it to indicate there is a provided way to do this. Just thought I would ask before I started making changes to stuff in my project. Thanks!

**Comment by jgdovin** [comment]
I came to look for the same thing, it seems that they removed file access, planning on adding it back myself today

**Comment by albinaask** [comment]
Well, the thing is that godot does that by default in [user://logs/godot.log]. So I decided that this feature was redundant and therefore removed it. If this is something you want and need, you are more than welcome to add it back in, make a PR if you want. I would like a max amount of saves stored though, so we don't end up with a GB folder of old and irrelevant logs.

**Comment by dehboxturtle** [comment]
Oh sweet I didn't know that Godot did this by default. That's good enough
for me! Sorry for the confusion!

**Comment by albinaask** [comment]
No, I was literally halfway through rewriting it when I realized that Godot already did it for me... It hasn't the feature of saving the say 10 latest instead of only the very latest if you want to compare different versions to find bugs etc, but I didn't bother setting that up for now. If someone wants it, Il do it (make chat GPT do it) then.
